%% load data
clear all; close all; clc;
load Testdata

L=15; % spatial domain
n=64; % Fourier modes
x2=linspace(-L,L,n+1); x=x2(1:n); y=x; z=x;
k=(2*pi/(2*L))*[0:(n/2-1) -n/2:-1]; ks=fftshift(k);

[X,Y,Z]=meshgrid(x,y,z);
[Kx,Ky,Kz]=meshgrid(ks,ks,ks);
[kx,ky,kz] = meshgrid(k,k,k); 

% plot the ultrasound data of the first measurement
figure(1);
Un1(:,:,:)=reshape(Undata(1,:),n,n,n);
isosurface(X,Y,Z,abs(Un1),0.4);
axis([-20 20 -20 20 -20 20]), grid on, drawnow
xlabel('x'); ylabel('y');zlabel('z');
title("measurement 1");
pause(1);
print(gcf,'-dpng','Figure1.png');

%% part 1
% Through averaging of the spectrum, determine the frequency signature 
% (center frequency) generated by the marble.

% Define uave as the average of all points in dataset
uave = zeros(n,n,n);

% Use for loop to calculate all measurement
for j=1:20
    Un(:,:,:)=reshape(Undata(j,:),n,n,n); % construct 3d matrix 
    u = fftn(Un); % frequency domain
    uave = uave + u;
end

% average the spectrum
specmax = max(max(max(abs(uave))));
specuave = abs(uave)/specmax;

% plot isosurface in frequency domain
close all;
figure(2);

isosurface(Kx,Ky,Kz,fftshift(specuave),0.6);
axis([-2*pi 2*pi -2*pi 2*pi -2*pi 2*pi]), grid on, drawnow;
xlabel('kx'); ylabel('ky');zlabel('kz');
title("Average data in frequency domain");
pause(2);
print(gcf,'-dpng','Figure2.png');

%% part 2
% Filter the data around the center frequency determined above in order to 
% denoise the data and determine the path of the marble.
close all;

% find max in frequency domain, which is the central frequency
[i, j, m] = ind2sub([n,n,n], find(fftshift(abs(uave)) == ...
    max(max(max(fftshift(abs(uave)))))));

% make a filter
filter = exp(-1.0*(kx-Kx(i,j,m)).^2) .* exp(-1.0*(ky-Ky(i,j,m)).^2) .* ...
    exp(-1.0*(kz-Kz(i,j,m)).^2);

% compute and plot the data
location = zeros(n,3);

figure(3); % for plotting the isosurface in spatial domain

 for l = 1:20
 % apply filter on each spectrum and ifft back
 Un(:,:,:)=reshape(Undata(l,:),n,n,n);
 unf = ifftn(filter.* (fftn(Un)));

 % locate the strongest signal
   [i1,j1,m1] = ind2sub([n,n,n], find(abs(unf) == max(max(max(abs(unf))))));
   location(l,:) = [X(i1,j1,m1), Y(i1,j1,m1), Z(i1,j1,m1)];
 end

 % plot the trajectory
plot3(location(:,1), location(:,2), location(:,3), 'g.-', 'MarkerSize', 20);
axis([-L L -L L -L L]);
title("path");
xlabel("x"); ylabel("y"); zlabel("z");
grid on, drawnow
print(gcf,'-dpng','Figure3.png');

%% part 3
% The location the intense acoustic wave should be focused to breakup the 
% marble at the 20th data measurement.

close all;

finallocation = location(20,:)